---
# tasks file for cisco-ios
- name: backup cisco config
  ios_config:
    backup: yes
    backup_options:
      dir_path: ./backup

- name: check device hostname
  ios_command:
    command:
      - show ip int br