---
# tasks file for cisco-ios
- name: backup cisco config
  ios_config:
    backup: yes
    backup_options:
      dir_path: ./backup

- name: check device interface status
  ios_command:
    commands: show ip int br
    wait_for: result[0] contains up
    register: up
    debug: msg="{{} up.stdout }"
    