---
- hosts: cisco_routers
  gather_facts: yes
  connection: network_cli

  tasks:
    - name: show run
      ios_command:
        commands:
          - show run
        hosts: "{{ ansible_host }}"
        username: cisco
        password: cisco
        when: ansible_network_os == ios
      register: config
      
    - name: save output to backup folder
      copy:
        content: "{{ config.stdout[0] }}"