---
- hosts: lab-r1
  gather_facts: true
  connection: network_cli
  ansible_network_os: ios

  tasks:
    - name: show run
      ios_command:
        commands:
          - show run
        hosts: "{{ ansible_host }}"
        username: cisco
        password: cisco
      register: config
      
    - name: save output to backup folder
      copy:
        content: "{{ config.stdout[0] }}"